import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Navbar from '../components/sections/Navbar'
import Hero from '../components/sections/Hero'
import News from '../components/sections/News'
import Prospective from '../components/sections/Prospective'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
      <div className='relative'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Navbar/>
     <Hero/>
     <News/>
     <Prospective/>
      </div>
      
  )
}
